
public enum TokenType
{
	PROGRAM_TOK, ID_TOK, END_TOK, IF_TOK, LEFT_PAREN_TOK, RIGHT_PAREN_TOK, ELSE_TOK,
	ASSIGNMENT_TOK, INT_TOK, LE_TOK, LT_TOK, GE_TOK, GT_TOK, EQ_TOK, NE_TOK, ADD_TOK, SUB_TOK,
	MUL_TOK, DIV_TOK, EOS_TOK, ELIF_TOK, EOL_TOK, MAIN_TOK, INDENT_TOK, COLON_TOK, WHILE_TOK, PRINT_TOK
}
